CREATE DATABASE book_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE db8;

CREATE TABLE books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    year INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
